name: Release build (all os and sdists)

on:
  workflow_dispatch:    
  
env:
  PYTHON_VERSION: '3.8'
  
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: apt-get-update
      run: sudo apt-get update
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: actions/checkout@v4
    - uses: PyO3/maturin-action@v1
      with:
        manylinux: auto
        command: build
        args: -m ./Cargo.toml --release -o linux_dist --find-interpreter 
        before-script-linux: |
          # If we're running on rhel centos, install needed packages.
          if command -v yum &> /dev/null; then
            yum update -y && yum install -y perl-core openssl openssl-devel pkgconfig libatomic perl-IPC-Cmd

            # If we're running on i686 we need to symlink libatomic
            # in order to build openssl with -latomic flag.
            if [[ ! -d "/usr/lib64" ]]; then
                ln -s /usr/lib/libatomic.so.1 /usr/lib/libatomic.so
            fi
          else
            # If we're running on debian-based system.
            apt update -y && apt-get install -y libssl-dev openssl pkg-config perl-IPC-Cmd 
          fi
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: linux_wheels
        path: linux_dist

  windows:
    runs-on: windows-latest
    steps:
    - name: SQLITE install
      run:  choco install sqlite -y
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: actions/checkout@v3
    - uses: PyO3/maturin-action@v1
      with:
        command: build
        args: -m ./Cargo.toml --release -o windows_dist --find-interpreter 
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: windows_wheels
        path: windows_dist


  macos-intel:
    runs-on: macos-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: actions/checkout@v3
    - uses: PyO3/maturin-action@v1
      with:
        command: build
        args: -v -m ./Cargo.toml --universal2 --release -o macos_dist --find-interpreter
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: macos_wheels
        path: macos_dist

  windows-sdist:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: PyO3/maturin-action@v1
      with:
        command: build
        args: -m ./Cargo.toml --sdist -o sdist --find-interpreter 
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: sdist
